import { spawn } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const backendDir = path.join(rootDir, "backend");
const frontendDir = path.join(rootDir, "frontend");
const backendEnvExamplePath = path.join(backendDir, ".env.example");
const backendEnvPath = path.join(backendDir, ".env");
const isWindows = process.platform === "win32";
const npmCommand = isWindows ? "npm.cmd" : "npm";
const dockerCommand = isWindows ? "docker.exe" : "docker";
const autogeneratedPlaceholder = "__AUTO_GENERATED__";

function log(message) {
  process.stdout.write(`[kms] ${message}\n`);
}

function logServiceSummary() {
  log("App startet. Standard-URLs:");
  log("Frontend: http://localhost:5173");
  log("Backend: http://localhost:3000");
  log("GraphiQL: http://localhost:3000/graphiql");
}

function createDefaultBackendEnv() {
  return [
    'DATABASE_URL="postgresql://postgres:password@localhost:5432/cargonaut?schema=public"',
    `JWT_SECRET="${autogeneratedPlaceholder}"`,
    'JWT_EXPIRES_IN="1d"',
    'PORT=3000',
    'UPLOADS_DIR="./uploads"',
    'PROFILE_UPLOAD_DIR="./uploads/profile"',
    'VEHICLE_UPLOAD_DIR="./uploads/vehicles"',
    'TRIP_UPLOAD_DIR="./uploads/trips"',
    "",
  ].join("\n");
}

function ensureBackendEnvExample() {
  const template = createDefaultBackendEnv();

  if (!existsSync(backendEnvExamplePath)) {
    writeFileSync(backendEnvExamplePath, template, "utf8");
    return template;
  }

  const existing = readFileSync(backendEnvExamplePath, "utf8");
  if (existing.trim().length === 0) {
    writeFileSync(backendEnvExamplePath, template, "utf8");
    return template;
  }

  return existing;
}

function parseEnvFile(content) {
  const result = new Map();

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const separatorIndex = line.indexOf("=");
    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    let value = line.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    result.set(key, value);
  }

  return result;
}

function serializeEnv(envMap) {
  return `${Array.from(envMap.entries(), ([key, value]) => `${key}="${value}"`).join("\n")}\n`;
}

function ensureBackendEnv() {
  const exampleContent = ensureBackendEnvExample();

  if (!existsSync(backendEnvPath) || readFileSync(backendEnvPath, "utf8").trim().length === 0) {
    copyFileSync(backendEnvExamplePath, backendEnvPath);
    log("`backend/.env` wurde aus `.env.example` vorbereitet.");
  }

  const envContent = readFileSync(backendEnvPath, "utf8");
  const envMap = parseEnvFile(envContent);
  const exampleMap = parseEnvFile(exampleContent);
  let changed = false;

  for (const [key, value] of exampleMap.entries()) {
    if (!envMap.has(key)) {
      envMap.set(key, value);
      changed = true;
    }
  }

  const jwtSecret = envMap.get("JWT_SECRET") ?? "";
  if (!jwtSecret || jwtSecret === autogeneratedPlaceholder) {
    envMap.set("JWT_SECRET", crypto.randomBytes(32).toString("hex"));
    changed = true;
    log("`JWT_SECRET` wurde automatisch generiert.");
  }

  const databaseUrl = envMap.get("DATABASE_URL") ?? "";
  if (!databaseUrl) {
    throw new Error("`backend/.env` enthaelt kein `DATABASE_URL`.");
  }

  if (changed) {
    writeFileSync(backendEnvPath, serializeEnv(envMap), "utf8");
  }
}

function pipeOutput(stream, writer, prefix) {
  if (!stream) {
    return;
  }

  stream.on("data", (chunk) => {
    const text = chunk.toString();
    for (const line of text.split(/\r?\n/)) {
      if (!line) {
        continue;
      }
      writer.write(`${prefix} ${line}\n`);
    }
  });
}

function run(command, args, options = {}) {
  const { cwd = rootDir, prefix } = options;

  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd,
      env: process.env,
      stdio: prefix ? ["inherit", "pipe", "pipe"] : "inherit",
    });

    if (prefix) {
      pipeOutput(child.stdout, process.stdout, prefix);
      pipeOutput(child.stderr, process.stderr, prefix);
    }

    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(
        new Error(
          `Command failed: ${[command, ...args].join(" ")} (${code ?? "unknown"})`,
        ),
      );
    });
  });
}

function spawnLongRunning(command, args, options = {}) {
  const { cwd = rootDir, prefix } = options;
  const child = spawn(command, args, {
    cwd,
    env: process.env,
    stdio: ["inherit", "pipe", "pipe"],
  });

  pipeOutput(child.stdout, process.stdout, prefix);
  pipeOutput(child.stderr, process.stderr, prefix);

  return child;
}

async function ensureDependencies() {
  const projects = [
    { name: "backend", dir: backendDir },
    { name: "frontend", dir: frontendDir },
  ];

  for (const project of projects) {
    const nodeModulesPath = path.join(project.dir, "node_modules");
    if (existsSync(nodeModulesPath)) {
      continue;
    }

    log(`Installiere Abhaengigkeiten fuer ${project.name}...`);
    await run(npmCommand, ["install"], { cwd: project.dir });
  }
}

async function prepareProject() {
  mkdirSync(path.join(backendDir, "uploads"), { recursive: true });
  ensureBackendEnv();
  await ensureDependencies();

  log("Starte PostgreSQL via Docker Compose...");
  await run(dockerCommand, ["compose", "up", "-d"], { cwd: backendDir });

  log("Generiere Prisma Client...");
  await run(npmCommand, ["run", "prisma:generate"], { cwd: backendDir });

  log("Wende Prisma Migrationen an...");
  await run(npmCommand, ["run", "prisma:migrate"], { cwd: backendDir });
}

async function runSetup() {
  await prepareProject();
  log("Setup abgeschlossen. Starte alles mit `npm run dev`.");
}

async function runDev() {
  await prepareProject();
  log("Starte Backend und Frontend...");

  const backend = spawnLongRunning(npmCommand, ["run", "start:dev"], {
    cwd: backendDir,
    prefix: "[backend]",
  });
  const frontend = spawnLongRunning(npmCommand, ["run", "dev"], {
    cwd: frontendDir,
    prefix: "[frontend]",
  });

  logServiceSummary();

  const children = [backend, frontend];
  let stopping = false;

  const stopChildren = (signal) => {
    if (stopping) {
      return;
    }

    stopping = true;
    log(`Beende Prozesse (${signal})...`);
    for (const child of children) {
      if (!child.killed) {
        child.kill(signal);
      }
    }
  };

  process.on("SIGINT", () => stopChildren("SIGINT"));
  process.on("SIGTERM", () => stopChildren("SIGTERM"));

  const exitCode = await Promise.race(
    children.map(
      (child) =>
        new Promise((resolve, reject) => {
          child.on("error", reject);
          child.on("exit", (code) => resolve(code ?? 0));
        }),
    ),
  );

  stopChildren("SIGTERM");
  process.exit(exitCode);
}

async function runSingleTarget(target) {
  if (target === "backend") {
    await prepareProject();
    await run(npmCommand, ["run", "start:dev"], { cwd: backendDir });
    return;
  }

  await ensureDependencies();
  await run(npmCommand, ["run", "dev"], { cwd: frontendDir });
}

async function runDbDown() {
  log("Stoppe PostgreSQL Container...");
  await run(dockerCommand, ["compose", "down"], { cwd: backendDir });
}

async function main() {
  const command = process.argv[2] ?? "dev";

  if (command === "setup") {
    await runSetup();
    return;
  }

  if (command === "dev") {
    await runDev();
    return;
  }

  if (command === "backend" || command === "frontend") {
    await runSingleTarget(command);
    return;
  }

  if (command === "db:down") {
    await runDbDown();
    return;
  }

  throw new Error(
    `Unbekannter Befehl: ${command}. Verfuegbar: dev, setup, backend, frontend, db:down`,
  );
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`[kms] Fehler: ${message}\n`);
  process.exit(1);
});
